### PR TITLE
Update Japanese to 2015-07-01

### PR DESCRIPTION
**Pull request by kotarot**
Here are the Japanese translations of 2015-07-01.

The contributors are:
* [Kotaro Terada (寺田晃太朗)](https://www.worldcubeassociation.org/results/p.php?i=2010TERA01)
* [Akihiro Ishida (石田朗大)](https://www.worldcubeassociation.org/results/p.php?i=2009ISHI01)
* [Kentaro Nishi (西賢太郎)](https://www.worldcubeassociation.org/results/p.php?i=2006NISH01)

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks!

**Comment by kotarot** [comment]
@lgarron Thanks, Lucas! Thank you for merging and uploading to WCA website. Could you also please change the contributors' name on the translation page into the above three members?
I mean this page: https://www.worldcubeassociation.org/regulations/translations/

**Comment by lgarron** [comment]
If the other people contributed to the original translation, shouldn't they still be credited?

**Comment by kotarot** [comment]
That's right, and they should still be credited, so we list up all contributors in [README](https://github.com/cubing/wca-regulations-translations/blob/master/japanese/README.md).

However enumerating these all people in the [translations page](https://www.worldcubeassociation.org/regulations/translations/) is too many, isn't it? Our idea is that the only main contributors, who translated the latest version (2015-07-01), are listed in that page.

Anyway, if you think all contributors should still be listed in that page, it is OK. We don't care about which is adopted. People currently listed are contributors for version-2013, please update it.

**Comment by lgarron** [comment]
I'd prefer to list past contributors, too. Does https://github.com/cubing/worldcubeassociation.org/commit/e6d7039d5706b2997d59c64b774a0252b21daa6d look alright?

**Comment by kotarot** [comment]
The change looks very nice, but could you append a link for "Shiori Sato (佐藤詩織)"? Her WCA ID is "2013SATO01". Thank you!

**Comment by lgarron** [comment]
Done.

**Pull request merged**
