### PR TITLE
Complete Japanese  translations for 2016-04-18

### PR DESCRIPTION
**Pull request by kotarot**
We have translated the latest guidelines and regulations. The following people helped with the translations for the latest one.
* [Kotaro Terada](https://www.worldcubeassociation.org/results/p.php?i=2010TERA01)
* [Kentaro Nishi](https://www.worldcubeassociation.org/results/p.php?i=2006NISH01)
* [Sinpei Araki](https://www.worldcubeassociation.org/results/p.php?i=2006ARAK01)
* [Akihiro Ishida](https://www.worldcubeassociation.org/results/p.php?i=2009ISHI01)

### CODE REVIEW

**Comment by Laura-O** [comment]
Although I don't understand a single word: looks good! Thank you! :-)

**Comment by kotarot** [comment]
Thanks! :smile:

**Comment by Claster** [comment]
Hi,

2e1 should be in a separate line, otherwise it isn't rendered correctly.

**Comment by viroulep** [comment]
Fixed in #41 :)

**Pull request merged**
