### PR TITLE
Portuguese-brazilian 2016 translation.

### PR DESCRIPTION
**Pull request by pedrosino**

### CODE REVIEW

**Comment by viroulep** [comment]
I took a look at the files, there is a bunch of issues:
- wca-regulations.md should be utf8 encoded (yes the compiler should be more clear about that, instead of crashing severely)
- Once you've fixed this it will error at the first line, could you please move the disclaimer that the translation is not official after the title in a separate (sub)section (such as a subsection of "Notas").
- I can't comment inline but line 526 of the Regulations:

> O Conselho da WCA deve aprovar

Starts with a space, please remove it.

Sorry for the non-clarity of the tool's output, I'll work on make it better!

After that the compiler will complain about a lot of Regulations being misplaced, you could push here again to see its output, but FYI this is what I get:

> Checking input file(s)...
Couldn't compile file, the following occured:
 - Error: Regulation 2i2 misplaced in section 2
 - Error: Regulation 3d1a misplaced in section 3d
 - Error: Regulation 3d1b misplaced in section 3d
 - Error: Regulation 3d2 misplaced in section 3d1b
 - Error: Regulation 3d3 misplaced in section 3d1b
 - Error: Regulation 3h2a misplaced in section 3h
 - Error: Regulation 3h3 misplaced in section 3h2a
 - Error: Regulation 3l1a misplaced in section 3l
 - Error: Regulation 3l1b misplaced in section 3l
 - Error: Regulation 4b2 misplaced in section 4b1
 - Error: Regulation 4b3a misplaced in section 4b
 - Error: Regulation 4b3b misplaced in section 4b
 - Error: Regulation 4b3c misplaced in section 4b
 - Error: Regulation 4b3d misplaced in section 4b
 - Error: Regulation 4b3e misplaced in section 4b
 - Error: Regulation 4b3f misplaced in section 4b
 - Error: Regulation 43d4 misplaced in section 4d
 - Error: Regulation 43d5 misplaced in section 4d
 - Error: Regulation 5b2 misplaced in section 5b1
 - Error: Regulation 5b3 misplaced in section 5b1
 - Error: Regulation 5b3a misplaced in section 5b1
 - Error: Regulation 5b3b misplaced in section 5b1
 - Error: Regulation 5b3c misplaced in section 5b1
 - Error: Regulation 5b4 misplaced in section 5b1
 - Error: Regulation 5b5 misplaced in section 5b1
 - Error: Regulation 5b5a misplaced in section 5b1
 - Error: Regulation 5b5b misplaced in section 5b1
 - Error: Regulation 5b5c misplaced in section 5b1
 - Error: Regulation 5b5d misplaced in section 5b1
 - Error: Regulation 5b5e misplaced in section 5b1
 - Error: Regulation 9b3b misplaced in section 9b
 - Error: Regulation 9f7 comes after 9f7 when it shouldn't
 - Error: Regulation 10h1 misplaced in section 10
 - Error: Regulation A2b1 misplaced in section A2
 - Error: Regulation A2d misplaced in section A2c
 - Error: Regulation A2d1 misplaced in section A2
 - Error: Regulation A2e misplaced in section A2d1
 - Error: Regulation A2e1 misplaced in section A
 - Error: Regulation A3a1 misplaced in section A3
 - Error: Regulation A3b1 misplaced in section A3
 - Error: Regulation A3b2 misplaced in section A3
 - Error: Regulation A3c1 misplaced in section A3
 - Error: Regulation A3c2 misplaced in section A3
 - Error: Regulation A3c3 misplaced in section A3
 - Error: Regulation A3c4 misplaced in section A3
 - Error: Regulation A3d misplaced in section A3c4
 - Error: Regulation A3d1 misplaced in section A3c4
 - Error: Regulation A3d2 misplaced in section A3c4
 - Error: Regulation A3d3 misplaced in section A3c4
 - Error: Regulation A4d misplaced in section A4b
 - Error: Regulation A4d1 misplaced in section A4b
 - Error: Regulation A4d2 misplaced in section A4b
 - Error: Regulation A4d3 misplaced in section A4
 - Error: Regulation a6i misplaced in section A6
 - Error: Regulation A7c2 misplaced in section A7
 - Error: Regulation B4d misplaced in section B4c
 - Error: Regulation B4e misplaced in section B4c
 - Error: Regulation B5b misplaced in section B5a
 - Error: Regulation B5c misplaced in section B5a
 - Error: Regulation C1c misplaced in section C1b
 - Error: Regulation E4d misplaced in section E3
 - Error: Regulation F3a misplaced in section F

Most of them are just indentation issues!
And finally, once you've fixed these it will check that your translation matches the official Regulations :)

Sorry, it seems painful but this process will ensure that the generated html and pdf available on the website are correct!

**Comment by viroulep** [comment]
Also note that if you install [`wrc`](https://github.com/cubing/wca-regulations-compiler) (via `pip install wrc` for instance), you can run the diff yourself without waiting for Travis by using `wrc path/to/portuguese/translation/directory --diff path/to/official/regulations/directory`

**Comment by pedrosino** [comment]
I tried running wrc, but don't know what is the
path/to/official/regulations/directory

wrc portuguese-brazilian/ --diff https://github.com/cubing/wca-regulations/
Checking input file(s)...
Syntax error on line -1
Unexpected TEXT
Traceback (most recent call last):
  File "/usr/local/bin/wrc", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/wrc/wrc.py", line 237, in run
    input_guidelines)
  File "/usr/local/lib/python2.7/dist-packages/wrc/wrc.py", line 34, in
parse_regulations_guidelines
    astreg, errors_reg, warnings_reg = parser.parse(reg_as_str,
WCARegulations)
  File "/usr/local/lib/python2.7/dist-packages/wrc/parse/parser.py", line
49, in parse
    ast = self.parser.parse(data, lexer=self.lexer)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in
parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1049, in
parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python2.7/dist-packages/ply/lex.py", line 350, in
token
    newtok = func(tok)
  File "/usr/local/lib/python2.7/dist-packages/wrc/parse/lexer.py", line
102, in t_TEXT
    text = token.lexer.lexmatch.group("text").decode("utf8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 49:
invalid continuation byte

**Comment by viroulep** [comment]
It's the path to the Regulations directory, so basically it would be the path to a local clone of the repository and not the remote repository itself.
Otherwise the `wrc` call is just right, and it complains that some characters are not utf8-decodable.
Since the Guidelines are [totally ok](https://travis-ci.org/cubing/wca-regulations-translations/builds/139633379#L230-L235), it's the `wca-regulations.md` file which turns out to be latin1-encoded.
The raw file [here](https://raw.githubusercontent.com/pedrosino/wca-regulations-translations/3b503fc682c5b0853587c3696c2728f0a01ce77d/portuguese-brazilian/wca-regulations.md) doesn't show all characters properly:
encoding.

Your favorite editor should have an "encoding" option that you can use to fix this and set the encoding to utf8; in vim it would be `set fileencoding=utf-8` and saving the file, in emacs I don't know but there is a  [wiki](https://www.emacswiki.org/emacs/ChangingEncodings) page for it, notepad++ has an "encoding->utf-8 without BOM" option.

**Comment by pedrosino** [comment]
wrc wca-regulations-translations/portuguese-brazilian/ --diff
wca-regulations-translations
Checking input file(s)...
Syntax error on line -1
Unexpected TEXT
All checks passed!
Checking reference file(s) for diff
Error: the directory 'wca-regulations-translations' must contain both the
Regulations and Guidelines files.

**Comment by viroulep** [comment]
The diff must be made against the official regulations!
So `wrc wca-regulations-translations/portuguese-brazilian/ --diff ../wca-regulations` for example, assuming you cloned `cubing/wca-regulations` in `../wca-regulations`.

However Travis is clear here, your translation is just missing a translation for [A1a4](https://travis-ci.org/cubing/wca-regulations-translations/builds/139817478#L243).

For some reason it didn't exit with an error on the first line when it should have: please move the disclaimer text from the very beginning of the file to one separate (sub)section (like it was before actually).

**Comment by viroulep** [comment]
Nice it's all good now!
Thanks for being so persistent, hopefully next time the errors will be much more visible and informative about what to do!

**Comment by pedrosino** [comment]
Hi again. I have no idea how it works, but do you plan on pushing this live soon?
We have a national competition on July 22 and would be cool to have the translation up as soon as possible.

**Comment by viroulep** [comment]
The latest version of the Regulations/translations are not built each time the website is deployed, I'll submit a PR updating them to the website repo later today.

**Pull request merged**
