### PR TITLE
German translation 2016-04-18

### PR DESCRIPTION
**Pull request by Laura-O**
This PR should be merged on Monday and might be updated meanwhile.

Apart from the update of the Regulations and Guidelines, I also removed old HTML files and images. I don't think they have any purpose and are just leftovers from old versions.

### CODE REVIEW

**Comment by viroulep** [comment]
You're right about the other files : the build system only cares about `wca-regulations.md` and `wca-guidelines.md`.

**Comment by viroulep** [comment]
@Laura-O, unless you have some last minutes changes to push, I'll merge this in about an hour.

**Comment by Laura-O** [comment]
Yes, everything checked and fine, thanks! :-)

**Comment by Claster** [comment]
Hi Laura,

Some remarks:

You forgot to translate F3a;
3h4 is missing;
A3d1 must be deleted;
you have 2 H1d+;
forgotted [Erklärung] at A1a2+++;
3d1a, 3d1b should be shifted left (they are not rendered correctly);
10h1, A2b1, B2b should be shifted right.

**Pull request merged**
