### PR TITLE
Update portuguese-european translation

### PR DESCRIPTION
**Pull request by cubizh**
As of July 1st official update.

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks!

**Comment by cubizh** [comment]
Since we're having a competition here this weekend, it would be great if you could update the website with these changes. Thanks :)

**Comment by lgarron** [comment]
Yeah, something went wrong last night because of the Japanese translation. :-/
Working on it right now.

**Comment by lgarron** [comment]
Should be fixed now.

**Pull request merged**
